[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.35"
optimizer = true
optimizer_runs = 200

# Filecoin networks. Use with: forge script ... --rpc-url calibration
[rpc_endpoints]
calibration = "https://api.calibration.node.glif.io/rpc/v1"
mainnet = "https://api.node.glif.io/rpc/v1"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
